config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  #get 'sessions/new'
  #get 'sessions/create'
  #get 'sessions/destroy'
  #resources :users

  root 'home#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
	  if session[:user_id]
      @current_user ||= User.find(session[:user_id])
      else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
   user = User.find_by_email(params[:email])
   if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email ou senha inválido"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
 end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "Usuário registrado!" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "Cadastro atualizado" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "Cadastro apagado!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :mobile, :email, :password, :password_confirmation, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="flex w-screen h-screen m-0 p-0 justify-center items-center bg-cover bg-no-repeat bg-center bg-[url('https://images.unsplash.com/photo-1605537964076-3cb0ea2ff329?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2032&q=80')]">

  <div class="flex flex-col justify-center items-center px-20 py-10 rounded-xl backdrop-blur-sm sm:py-10 md:p-5">
    <div class="text-white text-center  text-xl">
      
      Bem vindo ao 
      <p class="text-white font-bold text-4xl"> 
        Resort do Kuduairo
      </p>
    
    </div>

    <p class="text-white text-center text-sm pt-10">Somente bailarinos certificados podem visitar as instalações do presidente Gasulaina!</p>

    <div class="flex flex-col items-center mt-5"> 
      <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to 'Log Out', logout_path %>
      <% else %>

      <a class="mt-10" href= login>
        <button class="bg-white text-black px-6 py-2 rounded-full hover:">
          Entrar
        </button>
      </a>

      <a class="mt-10" href= signup>
        <button class="bg-teal-500 text-white px-6 shadow py-2 rounded-full hover:">
          Registrar
        </button>
      </a>

      <% end %>
    <!-- <p id='notice'><%= notice %></p> -->
    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resort do Kuduairo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<div class="flex w-screen h-screen m-0 p-0 justify-center items-center bg-cover bg-no-repeat bg-center bg-[url('https://images.unsplash.com/photo-1605537964076-3cb0ea2ff329?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2032&q=80')]">

<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="flex flex-col justify-center items-center px-20 py-10 rounded-xl backdrop-blur-sm sm:py-10 md:p-5">
    <div class=" text-center">

    <div class="flex text-start text-sm flex-col gap-5">

      <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
      </div>

      <div>
        <%= form.label :mobile, style: "display: block" %>
        <%= form.text_field :mobile %>
      </div>

      <div>
        <%= form.label :email, style: "display: block" %>
        <%= form.text_field :email %>
      </div>

      <div>
        <%= form.label :password, style: "display: block" %>
        <%= form.password_field :password %>
      </div>

      <div>
        <%= form.label :password_confirmation, style: "display: block" %>
        <%= form.password_field :password_confirmation %>
      </div>

      <div>
        <%= form.label :address, style: "display: block" %>
        <%= form.text_field :address %>
      </div>

      <div>
        <%= form.submit %>
      </div>
        <% end %>
    </div>

    </div>
  </div>

</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Mobile:</strong>
    <%= user.mobile %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= user.address %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Ver usuários", home_index_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Editar usuário", edit_user_path(@user) %> |
  <%= link_to "Voltar para usuários", users_path %>

  <%= button_to "Apagar registro de usuário", @user, method: :delete %>
</div>